name: employee
publish_to:
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  carousel_slider: ^2.2.1
  toast: ^0.1.5
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  firebase_database: ^3.1.6
  cloud_firestore: ^0.13.7
  font_awesome_flutter: ^8.8.1
  url_launcher: ^5.4.2
  rflutter_alert: ^1.0.3
  barcode_scan: ^3.0.1
  qr_flutter: ^3.2.0
  intl: ^0.16.1
  http: ^0.12.2
  shared_preferences: ^0.5.10
  date_util: ^0.1.4
  bubble_bottom_bar: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Dark
      fonts:
        - asset: fonts/dark.ttf

    - family: General
      fonts:
        - asset: fonts/Ubuntu.ttf

